apiVersion: v1
kind: Namespace
metadata:
  name: sse
  labels:
    name: sse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-oauth
  namespace: sse
  labels:
    app: spring-boot-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-oauth
  template:
    metadata:
      labels:
        app: spring-boot-oauth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: spring-boot-oauth
          image: shubham01/spring-boot-oauth:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 120
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 90
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: spring.datasource.url
              value: jdbc:mysql://mysql.sse-mysql.svc:3306/sse?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              value: root1234
            - name: spring.kafka.bootstrap-servers
              value: kafka-cluster.kafka.svc:9092
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-oauth
  namespace: sse
spec:
  selector:
    app: spring-boot-oauth
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-oauth
  namespace: sse
spec:
  rules:
    - http:
        paths:
          - path: /sse/*
            pathType: Prefix
            backend:
              service:
                name: spring-boot-oauth
                port:
                  number: 80

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-oauth-service-monitor
  namespace: sse
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: spring-boot-oauth
  endpoints:
    - port: http-traffic
      path: "/actuator/prometheus"
---