apiVersion: v1
kind: Namespace
metadata:
  name: sse-mysql
  labels:
    name: sse-mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: sse-mysql
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: sse-mysql
spec:
#  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: sse-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:latest
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root1234
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass-root
#                  key: password
#            - name: MYSQL_USER
#              value: root
#            - name: MYSQL_PASSWORD
#              value: root1234
#              valueFrom:
#                secretKeyRef:
#                  name: mysql-pass-user
#                  key: password
            - name: MYSQL_DATABASE
              value: sse
            # Use secret in real usage
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: sse-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
  clusterIP: None
---
#kind: Service
#apiVersion: v1
#metadata:
#  name: mysql
#  namespace: sse-mysql
#spec:
#  type: ExternalName
#  externalName: mysql.mysql.svc
#  ports:
#    - port: 3306
---
